import { canAccessWorkspace, canEdit, forbiddenResponse, getAuthenticatedUser, unauthorizedResponse } from "@/lib/auth";
import { readWhopCookie, whopOauthCookie } from "@/lib/whop-oauth";
import { deleteWhopOauthSession, getWhopOauthSession, saveWhopConnection } from "@/lib/whop-store";

async function validSession(request: Request, flowId: string) { if (!/^[a-zA-Z0-9_-]{32,}$/.test(flowId)) return null; const session = await getWhopOauthSession(flowId); const nonce = readWhopCookie(request); return session && nonce && session.browserNonce === nonce ? session : null; }

export async function GET(request: Request) { const user = await getAuthenticatedUser(request.headers); if (!user) return unauthorizedResponse(); if (!canEdit(user)) return forbiddenResponse(); const session = await validSession(request, new URL(request.url).searchParams.get("flow") ?? ""); if (!session) return Response.json({ error: "This Whop connection session expired. Please start again." }, { status: 410 }); if (!canAccessWorkspace(user, session.workspaceId)) return forbiddenResponse(); return Response.json({ accounts: session.accounts ?? [] }, { headers: { "cache-control": "no-store" } }); }

export async function POST(request: Request) { const user = await getAuthenticatedUser(request.headers); if (!user) return unauthorizedResponse(); if (!canEdit(user)) return forbiddenResponse(); const body = await request.json() as { flow?: string; accountId?: string }; const session = await validSession(request, body.flow ?? ""); if (!session || !session.accessToken || !session.refreshToken || !session.tokenExpiresAt) return Response.json({ error: "This Whop connection session expired. Please start again." }, { status: 410 }); if (!canAccessWorkspace(user, session.workspaceId)) return forbiddenResponse(); const account = session.accounts?.find((item) => item.id === body.accountId); if (!account) return Response.json({ error: "Choose one of the authorized Whop accounts." }, { status: 400 }); await saveWhopConnection({ workspaceId: session.workspaceId, accountId: account.id, accountName: account.name, accessToken: session.accessToken, refreshToken: session.refreshToken, tokenExpiresAt: session.tokenExpiresAt }); await deleteWhopOauthSession(session.id); const response = Response.json({ ok: true }); response.headers.append("set-cookie", whopOauthCookie("", request, 0)); return response; }
