"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Account = { id: string; name: string; status?: string };
export default function WhopAccountSelection() {
  const [flow] = useState(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("flow") ?? ""); const [accounts, setAccounts] = useState<Account[]>([]); const [selected, setSelected] = useState(""); const [status, setStatus] = useState(() => flow ? "Loading your Whop accounts…" : "This connection link is invalid."); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!flow) return; void fetch(`/api/whop/oauth/complete?flow=${encodeURIComponent(flow)}`, { cache: "no-store" }).then(async (response) => { const result = await response.json() as { accounts?: Account[]; error?: string }; if (!response.ok || !result.accounts?.length) { setStatus(result.error || "No Whop accounts were found."); return; } setAccounts(result.accounts); setSelected(result.accounts[0].id); setStatus(""); }).catch(() => setStatus("Your Whop accounts could not be loaded.")); }, [flow]);
  async function connect(event: React.FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); const response = await fetch("/api/whop/oauth/complete", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ flow, accountId: selected }) }); const result = await response.json() as { error?: string }; if (!response.ok) { setStatus(result.error || "This Whop account could not be connected."); setSaving(false); return; } window.location.assign("/?whop=connected"); }
  return <main className="meta-select-shell whop-select-shell"><form className="meta-select-card" onSubmit={connect}><div className="meta-select-brand"><span>MR</span><strong>MoonRift</strong></div><div className="meta-select-icon whop-select-icon">W</div><h1>Choose a Whop account</h1><p>Select the Whop business account MoonRift should use for campaign spend and performance reporting.</p>{status && <div className="meta-select-status">{status}</div>}<div className="meta-account-list">{accounts.map((account) => <label className={selected === account.id ? "selected" : ""} key={account.id}><input type="radio" checked={selected === account.id} onChange={() => setSelected(account.id)} /><span><b>{account.name}</b><small>{account.id} · {account.status || "Available"}</small></span><i>{selected === account.id ? "✓" : ""}</i></label>)}</div><button type="submit" disabled={!selected || saving}>{saving ? "Connecting…" : "Connect selected account"}</button><Link href="/?whop=cancelled">Cancel</Link></form></main>;
}
